import type { Book } from "./types";

/**
 * A small seeded catalog. It is deliberately opinionated rather than
 * exhaustive: every field here is one the ranking in
 * `recommender/localRecommender.ts` actually reads.
 *
 * The four books shown in the Figma "Recommendation" frame (283:203) carry
 * their exact displayed rating, ratings count and year so the sample query
 * from the design reproduces that screen.
 */
export const CATALOG: Book[] = [
  {
    id: "dungeon-crawler-carl",
    title: "Dungeon Crawler Carl",
    author: "Matt Dinniman",
    rating: 4.46,
    ratingsCount: 384129,
    year: 2020,
    pages: 384,
    format: "novel",
    genres: ["science fiction", "fantasy"],
    moods: ["funny", "adventurous", "tense"],
    subjects: ["litrpg", "dungeon", "survival", "gaming", "apocalypse", "aliens"],
    pace: "fast",
    adaptation: { kind: "film", note: "is slated for movie adaptation" },
    cover: { from: "#f4c430", to: "#c2410c", ink: "#1b1b1b" },
  },
  {
    id: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    rating: 4.51,
    ratingsCount: 5434343,
    year: 2021,
    pages: 496,
    format: "novel",
    genres: ["science fiction"],
    moods: ["hopeful", "funny", "tense", "adventurous"],
    subjects: ["space", "first contact", "aliens", "survival", "science", "problem solving"],
    pace: "fast",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#0b1d3a", to: "#1e4f8f", ink: "#f5f5f5" },
  },
  {
    id: "annihilation",
    title: "Annihilation",
    author: "Jeff VanderMeer",
    rating: 3.8,
    ratingsCount: 318585,
    year: 2014,
    pages: 195,
    format: "novel",
    genres: ["science fiction", "horror", "literary fiction"],
    moods: ["unsettling", "bleak", "contemplative"],
    subjects: ["expedition", "ecology", "weird fiction", "aliens", "wilderness"],
    pace: "medium",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#0f3d2e", to: "#123f24", ink: "#c9f2c7" },
  },
  {
    id: "stories-of-your-life",
    title: "Stories of Your Life and Others",
    author: "Ted Chiang",
    rating: 4.25,
    ratingsCount: 129149,
    year: 2010,
    pages: 281,
    format: "collection",
    genres: ["science fiction", "literary fiction"],
    moods: ["contemplative", "melancholy", "hopeful"],
    subjects: ["linguistics", "first contact", "time", "aliens", "short stories", "mathematics"],
    pace: "slow",
    adaptation: { kind: "film", note: "contains the short story adapted into the movie Arrival" },
    cover: { from: "#1c1c28", to: "#4b3f72", ink: "#ecebf5" },
  },

  /* --- more science fiction --- */
  {
    id: "children-of-time",
    title: "Children of Time",
    author: "Adrian Tchaikovsky",
    rating: 4.31,
    ratingsCount: 258441,
    year: 2015,
    pages: 600,
    format: "novel",
    genres: ["science fiction"],
    moods: ["contemplative", "tense", "hopeful"],
    subjects: ["space", "evolution", "spiders", "terraforming", "aliens"],
    pace: "medium",
    cover: { from: "#123027", to: "#2f6b4f", ink: "#e8f6ee" },
  },
  {
    id: "the-martian",
    title: "The Martian",
    author: "Andy Weir",
    rating: 4.42,
    ratingsCount: 1361204,
    year: 2011,
    pages: 369,
    format: "novel",
    genres: ["science fiction"],
    moods: ["funny", "hopeful", "tense"],
    subjects: ["space", "mars", "survival", "science", "problem solving"],
    pace: "fast",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#8c2f0d", to: "#d97706", ink: "#fff7ed" },
  },
  {
    id: "dune",
    title: "Dune",
    author: "Frank Herbert",
    rating: 4.27,
    ratingsCount: 1489302,
    year: 1965,
    pages: 658,
    format: "novel",
    genres: ["science fiction"],
    moods: ["tense", "contemplative", "adventurous"],
    subjects: ["desert", "empire", "politics", "ecology", "messiah"],
    pace: "slow",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#b45309", to: "#78350f", ink: "#fef3c7" },
  },
  {
    id: "the-three-body-problem",
    title: "The Three-Body Problem",
    author: "Cixin Liu",
    rating: 4.08,
    ratingsCount: 442117,
    year: 2008,
    pages: 400,
    format: "novel",
    genres: ["science fiction"],
    moods: ["unsettling", "contemplative", "tense"],
    subjects: ["first contact", "physics", "aliens", "history", "china"],
    pace: "medium",
    adaptation: { kind: "tv", note: "has been adapted for television" },
    cover: { from: "#1e293b", to: "#0f766e", ink: "#e2f4f1" },
  },
  {
    id: "station-eleven",
    title: "Station Eleven",
    author: "Emily St. John Mandel",
    rating: 4.06,
    ratingsCount: 738912,
    year: 2014,
    pages: 333,
    format: "novel",
    genres: ["science fiction", "literary fiction"],
    moods: ["melancholy", "hopeful", "contemplative"],
    subjects: ["pandemic", "apocalypse", "theatre", "art", "memory"],
    pace: "medium",
    adaptation: { kind: "tv", note: "has been adapted into a self-titled television series" },
    cover: { from: "#0b2545", to: "#134e6f", ink: "#eaf4fb" },
  },
  {
    id: "a-memory-called-empire",
    title: "A Memory Called Empire",
    author: "Arkady Martine",
    rating: 4.12,
    ratingsCount: 92310,
    year: 2019,
    pages: 462,
    format: "novel",
    genres: ["science fiction"],
    moods: ["tense", "contemplative"],
    subjects: ["empire", "politics", "language", "identity", "space"],
    pace: "medium",
    cover: { from: "#3b0764", to: "#7e22ce", ink: "#f3e8ff" },
  },
  {
    id: "the-long-way",
    title: "The Long Way to a Small, Angry Planet",
    author: "Becky Chambers",
    rating: 4.17,
    ratingsCount: 214088,
    year: 2014,
    pages: 518,
    format: "novel",
    genres: ["science fiction"],
    moods: ["cozy", "hopeful", "funny"],
    subjects: ["space", "found family", "aliens", "travel"],
    pace: "slow",
    cover: { from: "#0e7490", to: "#a21caf", ink: "#f0fdfa" },
  },
  {
    id: "exhalation",
    title: "Exhalation",
    author: "Ted Chiang",
    rating: 4.25,
    ratingsCount: 61240,
    year: 2019,
    pages: 350,
    format: "collection",
    genres: ["science fiction", "literary fiction"],
    moods: ["contemplative", "hopeful", "melancholy"],
    subjects: ["short stories", "time", "free will", "science", "memory"],
    pace: "slow",
    cover: { from: "#164e63", to: "#0891b2", ink: "#ecfeff" },
  },
  {
    id: "recursion",
    title: "Recursion",
    author: "Blake Crouch",
    rating: 4.16,
    ratingsCount: 314778,
    year: 2019,
    pages: 329,
    format: "novel",
    genres: ["science fiction", "thriller"],
    moods: ["tense", "melancholy"],
    subjects: ["memory", "time", "science", "grief"],
    pace: "fast",
    cover: { from: "#111827", to: "#b91c1c", ink: "#fee2e2" },
  },
  {
    id: "klara-and-the-sun",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    rating: 3.75,
    ratingsCount: 289453,
    year: 2021,
    pages: 303,
    format: "novel",
    genres: ["science fiction", "literary fiction"],
    moods: ["melancholy", "contemplative", "hopeful"],
    subjects: ["artificial intelligence", "childhood", "illness", "love"],
    pace: "slow",
    cover: { from: "#fde68a", to: "#f59e0b", ink: "#3f2d0b" },
  },
  {
    id: "sea-of-tranquility",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
    rating: 4.09,
    ratingsCount: 246015,
    year: 2022,
    pages: 259,
    format: "novel",
    genres: ["science fiction", "literary fiction"],
    moods: ["melancholy", "contemplative", "hopeful"],
    subjects: ["time", "pandemic", "simulation", "moon"],
    pace: "medium",
    cover: { from: "#1e3a8a", to: "#60a5fa", ink: "#eff6ff" },
  },

  /* --- fantasy --- */
  {
    id: "he-who-fights-with-monsters",
    title: "He Who Fights with Monsters",
    author: "Shirtaloon",
    rating: 4.28,
    ratingsCount: 96412,
    year: 2021,
    pages: 636,
    format: "novel",
    genres: ["fantasy"],
    moods: ["funny", "adventurous"],
    subjects: ["litrpg", "isekai", "dungeon", "gaming", "progression"],
    pace: "fast",
    cover: { from: "#7f1d1d", to: "#f59e0b", ink: "#fff7ed" },
  },
  {
    id: "cradle-unsouled",
    title: "Unsouled",
    author: "Will Wight",
    rating: 4.19,
    ratingsCount: 82304,
    year: 2016,
    pages: 286,
    format: "novel",
    genres: ["fantasy"],
    moods: ["adventurous", "hopeful"],
    subjects: ["progression", "martial arts", "cultivation", "gaming"],
    pace: "fast",
    cover: { from: "#134e4a", to: "#22d3ee", ink: "#042f2e" },
  },
  {
    id: "the-name-of-the-wind",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    rating: 4.52,
    ratingsCount: 1002418,
    year: 2007,
    pages: 662,
    format: "novel",
    genres: ["fantasy"],
    moods: ["adventurous", "melancholy", "contemplative"],
    subjects: ["magic school", "music", "storytelling", "orphan"],
    pace: "medium",
    cover: { from: "#1c1917", to: "#78350f", ink: "#fef3c7" },
  },
  {
    id: "piranesi",
    title: "Piranesi",
    author: "Susanna Clarke",
    rating: 4.24,
    ratingsCount: 312904,
    year: 2020,
    pages: 245,
    format: "novel",
    genres: ["fantasy", "literary fiction"],
    moods: ["unsettling", "contemplative", "melancholy"],
    subjects: ["labyrinth", "memory", "isolation", "wonder"],
    pace: "slow",
    cover: { from: "#e7e5e4", to: "#a8a29e", ink: "#1c1917" },
  },
  {
    id: "the-fifth-season",
    title: "The Fifth Season",
    author: "N. K. Jemisin",
    rating: 4.35,
    ratingsCount: 322870,
    year: 2015,
    pages: 468,
    format: "novel",
    genres: ["fantasy", "science fiction"],
    moods: ["bleak", "tense", "contemplative"],
    subjects: ["apocalypse", "geology", "oppression", "motherhood"],
    pace: "medium",
    cover: { from: "#3f0d0d", to: "#ea580c", ink: "#ffedd5" },
  },
  {
    id: "the-hobbit",
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    rating: 4.29,
    ratingsCount: 3844911,
    year: 1937,
    pages: 310,
    format: "novel",
    genres: ["fantasy"],
    moods: ["cozy", "adventurous", "funny"],
    subjects: ["quest", "dragon", "friendship", "wilderness"],
    pace: "medium",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#14532d", to: "#65a30d", ink: "#f7fee7" },
  },

  /* --- literary & historical --- */
  {
    id: "never-let-me-go",
    title: "Never Let Me Go",
    author: "Kazuo Ishiguro",
    rating: 3.85,
    ratingsCount: 890114,
    year: 2005,
    pages: 288,
    format: "novel",
    genres: ["literary fiction", "science fiction"],
    moods: ["melancholy", "bleak", "contemplative"],
    subjects: ["boarding school", "cloning", "friendship", "mortality"],
    pace: "slow",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#cbd5e1", to: "#64748b", ink: "#0f172a" },
  },
  {
    id: "a-little-life",
    title: "A Little Life",
    author: "Hanya Yanagihara",
    rating: 4.28,
    ratingsCount: 512903,
    year: 2015,
    pages: 720,
    format: "novel",
    genres: ["literary fiction"],
    moods: ["bleak", "melancholy"],
    subjects: ["friendship", "trauma", "new york", "art"],
    pace: "slow",
    cover: { from: "#111827", to: "#374151", ink: "#f9fafb" },
  },
  {
    id: "normal-people",
    title: "Normal People",
    author: "Sally Rooney",
    rating: 3.84,
    ratingsCount: 1104882,
    year: 2018,
    pages: 266,
    format: "novel",
    genres: ["literary fiction", "romance"],
    moods: ["melancholy", "romantic", "contemplative"],
    subjects: ["class", "ireland", "university", "love"],
    pace: "medium",
    adaptation: { kind: "tv", note: "has been adapted into a self-titled television series" },
    cover: { from: "#fecdd3", to: "#9f1239", ink: "#4c0519" },
  },
  {
    id: "the-remains-of-the-day",
    title: "The Remains of the Day",
    author: "Kazuo Ishiguro",
    rating: 4.13,
    ratingsCount: 218477,
    year: 1989,
    pages: 258,
    format: "novel",
    genres: ["literary fiction", "historical fiction"],
    moods: ["melancholy", "contemplative"],
    subjects: ["england", "service", "regret", "war"],
    pace: "slow",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#292524", to: "#78716c", ink: "#fafaf9" },
  },
  {
    id: "the-overstory",
    title: "The Overstory",
    author: "Richard Powers",
    rating: 4.06,
    ratingsCount: 234519,
    year: 2018,
    pages: 502,
    format: "novel",
    genres: ["literary fiction"],
    moods: ["contemplative", "hopeful", "melancholy"],
    subjects: ["trees", "ecology", "activism", "wilderness"],
    pace: "slow",
    cover: { from: "#14532d", to: "#4d7c0f", ink: "#ecfccb" },
  },
  {
    id: "beloved",
    title: "Beloved",
    author: "Toni Morrison",
    rating: 3.96,
    ratingsCount: 456210,
    year: 1987,
    pages: 324,
    format: "novel",
    genres: ["literary fiction", "historical fiction"],
    moods: ["bleak", "unsettling", "contemplative"],
    subjects: ["slavery", "memory", "motherhood", "ghosts"],
    pace: "slow",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#450a0a", to: "#991b1b", ink: "#fee2e2" },
  },
  {
    id: "wolf-hall",
    title: "Wolf Hall",
    author: "Hilary Mantel",
    rating: 3.9,
    ratingsCount: 224613,
    year: 2009,
    pages: 604,
    format: "novel",
    genres: ["historical fiction", "literary fiction"],
    moods: ["tense", "contemplative"],
    subjects: ["tudor", "politics", "england", "power"],
    pace: "slow",
    adaptation: { kind: "tv", note: "has been adapted into a self-titled television series" },
    cover: { from: "#1e1b4b", to: "#4338ca", ink: "#e0e7ff" },
  },

  /* --- mystery, thriller, horror --- */
  {
    id: "the-secret-history",
    title: "The Secret History",
    author: "Donna Tartt",
    rating: 4.17,
    ratingsCount: 802441,
    year: 1992,
    pages: 559,
    format: "novel",
    genres: ["mystery", "literary fiction"],
    moods: ["unsettling", "tense", "melancholy"],
    subjects: ["college", "greek", "murder", "class"],
    pace: "medium",
    cover: { from: "#052e16", to: "#166534", ink: "#dcfce7" },
  },
  {
    id: "gone-girl",
    title: "Gone Girl",
    author: "Gillian Flynn",
    rating: 4.11,
    ratingsCount: 2891044,
    year: 2012,
    pages: 415,
    format: "novel",
    genres: ["thriller", "mystery"],
    moods: ["tense", "unsettling"],
    subjects: ["marriage", "missing person", "media", "revenge"],
    pace: "fast",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#0f172a", to: "#facc15", ink: "#fefce8" },
  },
  {
    id: "the-thursday-murder-club",
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    rating: 3.94,
    ratingsCount: 512377,
    year: 2020,
    pages: 382,
    format: "novel",
    genres: ["mystery"],
    moods: ["cozy", "funny"],
    subjects: ["retirement", "friendship", "murder", "england"],
    pace: "medium",
    adaptation: { kind: "film", note: "has been made into a self-titled major motion picture" },
    cover: { from: "#0891b2", to: "#84cc16", ink: "#052e16" },
  },
  {
    id: "mexican-gothic",
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    rating: 3.66,
    ratingsCount: 542188,
    year: 2020,
    pages: 301,
    format: "novel",
    genres: ["horror", "historical fiction"],
    moods: ["unsettling", "tense"],
    subjects: ["haunted house", "mexico", "family", "fungus"],
    pace: "medium",
    cover: { from: "#4a044e", to: "#be123c", ink: "#fdf2f8" },
  },
  {
    id: "the-haunting-of-hill-house",
    title: "The Haunting of Hill House",
    author: "Shirley Jackson",
    rating: 3.88,
    ratingsCount: 285930,
    year: 1959,
    pages: 182,
    format: "novel",
    genres: ["horror"],
    moods: ["unsettling", "bleak"],
    subjects: ["haunted house", "isolation", "psychology", "ghosts"],
    pace: "medium",
    adaptation: { kind: "tv", note: "has been adapted into a self-titled television series" },
    cover: { from: "#18181b", to: "#3f3f46", ink: "#e4e4e7" },
  },

  /* --- romance --- */
  {
    id: "the-seven-husbands",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    rating: 4.44,
    ratingsCount: 3210466,
    year: 2017,
    pages: 389,
    format: "novel",
    genres: ["historical fiction", "romance"],
    moods: ["romantic", "melancholy"],
    subjects: ["hollywood", "fame", "queer love", "secrets"],
    pace: "fast",
    cover: { from: "#065f46", to: "#10b981", ink: "#ecfdf5" },
  },
  {
    id: "beach-read",
    title: "Beach Read",
    author: "Emily Henry",
    rating: 3.93,
    ratingsCount: 1042377,
    year: 2020,
    pages: 361,
    format: "novel",
    genres: ["romance"],
    moods: ["funny", "romantic", "hopeful"],
    subjects: ["writers", "grief", "small town", "summer"],
    pace: "fast",
    cover: { from: "#fbbf24", to: "#f97316", ink: "#431407" },
  },

  /* --- nonfiction, memoir, essays, poetry --- */
  {
    id: "notebooks-1942-1951",
    title: "Notebooks 1942-1951",
    author: "Albert Camus",
    rating: 4.32,
    ratingsCount: 4127,
    year: 1965,
    pages: 288,
    format: "nonfiction",
    genres: ["nonfiction", "essays"],
    moods: ["contemplative", "melancholy", "bleak"],
    subjects: ["philosophy", "absurdism", "war", "writing", "france"],
    pace: "slow",
    cover: { from: "#e7e5e4", to: "#d6d3d1", ink: "#1c1917" },
  },
  {
    id: "the-myth-of-sisyphus",
    title: "The Myth of Sisyphus",
    author: "Albert Camus",
    rating: 4.19,
    ratingsCount: 98204,
    year: 1942,
    pages: 212,
    format: "nonfiction",
    genres: ["nonfiction", "essays"],
    moods: ["contemplative", "bleak"],
    subjects: ["philosophy", "absurdism", "meaning", "france"],
    pace: "slow",
    cover: { from: "#1c1917", to: "#57534e", ink: "#fafaf9" },
  },
  {
    id: "the-year-of-magical-thinking",
    title: "The Year of Magical Thinking",
    author: "Joan Didion",
    rating: 3.93,
    ratingsCount: 217890,
    year: 2005,
    pages: 227,
    format: "nonfiction",
    genres: ["memoir", "nonfiction"],
    moods: ["melancholy", "contemplative", "bleak"],
    subjects: ["grief", "marriage", "writing", "mortality"],
    pace: "slow",
    cover: { from: "#0c4a6e", to: "#0369a1", ink: "#f0f9ff" },
  },
  {
    id: "braiding-sweetgrass",
    title: "Braiding Sweetgrass",
    author: "Robin Wall Kimmerer",
    rating: 4.51,
    ratingsCount: 271044,
    year: 2013,
    pages: 391,
    format: "nonfiction",
    genres: ["nonfiction", "essays"],
    moods: ["hopeful", "contemplative", "cozy"],
    subjects: ["ecology", "indigenous knowledge", "plants", "gratitude"],
    pace: "slow",
    cover: { from: "#4d7c0f", to: "#a3e635", ink: "#1a2e05" },
  },
  {
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    rating: 4.35,
    ratingsCount: 1092446,
    year: 2011,
    pages: 443,
    format: "nonfiction",
    genres: ["nonfiction"],
    moods: ["contemplative"],
    subjects: ["history", "anthropology", "science", "civilization"],
    pace: "medium",
    cover: { from: "#78350f", to: "#d97706", ink: "#fffbeb" },
  },
  {
    id: "devotions",
    title: "Devotions",
    author: "Mary Oliver",
    rating: 4.56,
    ratingsCount: 62190,
    year: 2017,
    pages: 480,
    format: "collection",
    genres: ["poetry"],
    moods: ["hopeful", "contemplative", "cozy"],
    subjects: ["nature", "attention", "wilderness", "gratitude"],
    pace: "slow",
    cover: { from: "#065f46", to: "#34d399", ink: "#022c22" },
  },
];

const BY_ID = new Map(CATALOG.map((book) => [book.id, book]));

export function getBook(id: string): Book | undefined {
  return BY_ID.get(id);
}

/** Throws when an id is unknown — used where a missing book is a bug, not input. */
export function requireBook(id: string): Book {
  const book = BY_ID.get(id);
  if (!book) throw new Error(`Unknown book id: ${id}`);
  return book;
}
