/// <reference types="next/image-types/global" />

// Declares the `*.webp` (and friends) modules that src/covers/index.ts imports.
//
// These normally arrive via next-env.d.ts, but that file is generated by
// `next build` and is gitignored, so on a fresh checkout it does not exist yet
// — and CI runs `typecheck` before `build`. This file makes the typecheck
// independent of whether anything has been built.
//
// Referencing the same types next-env.d.ts references is idempotent, so this
// does not conflict once that file has been generated.
