#!/usr/bin/env node
/**
 * Turns cover artwork in assets/covers-src/ into the WebP files the app ships.
 *
 *   npm run covers
 *
 * Source files are named after the book id in src/lib/catalog.ts, with any of
 * the extensions below — e.g. assets/covers-src/annihilation.jpg. Each is
 * resized to 210x315 WebP in src/covers/, which is 3x the 70x105 box the result
 * rows render, so it stays sharp on a retina screen without bloating the repo.
 *
 * Missing sources are reported and skipped, not treated as errors: the app
 * falls back to generated art for any book with no image, which is the normal
 * state for most of the catalog.
 */
import { existsSync } from "node:fs";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC_DIR = path.join(ROOT, "assets", "covers-src");
const OUT_DIR = path.join(ROOT, "src", "covers");

/** Cover box in CSS pixels (BookRow renders 70x105), times three for retina. */
const WIDTH = 210;
const HEIGHT = 315;
const QUALITY = 82;

const EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".avif", ".tiff"];

/** Book ids that may have real cover art. Must match src/lib/catalog.ts. */
const BOOK_IDS = [
  "dungeon-crawler-carl",
  "project-hail-mary",
  "annihilation",
  "stories-of-your-life",
];

function findSource(files, id) {
  for (const extension of EXTENSIONS) {
    const match = files.find((f) => f.toLowerCase() === `${id}${extension}`);
    if (match) return match;
  }
  return null;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const files = existsSync(SRC_DIR) ? await readdir(SRC_DIR) : [];
  const written = [];
  const missing = [];

  for (const id of BOOK_IDS) {
    const source = findSource(files, id);
    if (!source) {
      missing.push(id);
      continue;
    }

    const from = path.join(SRC_DIR, source);
    const to = path.join(OUT_DIR, `${id}.webp`);
    const { width, height } = await sharp(from).metadata();

    await sharp(from)
      // "cover" crops rather than squashes. Every cover is already close to
      // 2:3, so the crop is a few percent off the long edge at most.
      .resize(WIDTH, HEIGHT, { fit: "cover", position: "centre" })
      .webp({ quality: QUALITY })
      .toFile(to);

    written.push({ id, source, from: `${width}x${height}` });
  }

  await writeIndex(written.map((w) => w.id));

  for (const { id, source, from } of written) {
    console.log(`  ok    ${id}  ${source} (${from}) -> ${WIDTH}x${HEIGHT} webp`);
  }
  for (const id of missing) {
    console.log(`  skip  ${id}  no source found in assets/covers-src/`);
  }

  if (written.length === 0) {
    console.log(
      "\nNo cover sources present. Every book keeps its generated art;\n" +
        "drop files named <book-id>.jpg into assets/covers-src/ and re-run.",
    );
  } else {
    console.log(`\nWrote ${written.length} cover(s) to src/covers/.`);
  }
}

/**
 * Regenerates src/covers/index.ts. Static imports are what let Next rewrite
 * the URLs for `basePath` — a literal "/covers/x.webp" would 404 under
 * /book-rec/ on GitHub Pages.
 */
async function writeIndex(ids) {
  const header = `// GENERATED BY scripts/prepare-covers.mjs — DO NOT EDIT BY HAND.
// Run \`npm run covers\` after adding or replacing artwork in assets/covers-src/.
import type { StaticImageData } from "next/image";
`;

  const imports = ids
    .map((id) => `import ${camel(id)} from "./${id}.webp";`)
    .join("\n");

  const entries = ids.map((id) => `  "${id}": ${camel(id)},`).join("\n");

  const body = `
/** Real cover art, keyed by the book id. Books absent here use generated art. */
export const COVER_IMAGES: Record<string, StaticImageData> = {
${entries}
};
`;

  const contents = ids.length === 0
    ? `${header}
/** Real cover art, keyed by the book id. Books absent here use generated art. */
export const COVER_IMAGES: Record<string, StaticImageData> = {};
`
    : `${header}${imports}\n${body}`;

  await writeFile(path.join(OUT_DIR, "index.ts"), contents, "utf8");
}

function camel(id) {
  return id.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

await main();
