// GENERATED BY scripts/prepare-covers.mjs — DO NOT EDIT BY HAND.
// Run `npm run covers` after adding or replacing artwork in assets/covers-src/.
import type { StaticImageData } from "next/image";
import dungeonCrawlerCarl from "./dungeon-crawler-carl.webp";
import projectHailMary from "./project-hail-mary.webp";
import annihilation from "./annihilation.webp";
import storiesOfYourLife from "./stories-of-your-life.webp";

/** Real cover art, keyed by the book id. Books absent here use generated art. */
export const COVER_IMAGES: Record<string, StaticImageData> = {
  "dungeon-crawler-carl": dungeonCrawlerCarl,
  "project-hail-mary": projectHailMary,
  "annihilation": annihilation,
  "stories-of-your-life": storiesOfYourLife,
};
