// GENERATED BY scripts/prepare-covers.mjs — DO NOT EDIT BY HAND.
// Run `npm run covers` after adding or replacing artwork in assets/covers-src/.
import type { StaticImageData } from "next/image";

/** Real cover art, keyed by the book id. Books absent here use generated art. */
export const COVER_IMAGES: Record<string, StaticImageData> = {};
